from typing import List, Optional
from pydantic import BaseModel, Field


class AIChatRequest(BaseModel):
    """Schema for user query sent to AI assistant."""
    message: str = Field(..., min_length=1, description="User question or prompt for AI Assistant")


class AIChatResponse(BaseModel):
    """Schema for response returned by AI assistant."""
    response: str = Field(..., description="Groq AI generated natural language response")
    timestamp: str = Field(..., description="Timestamp of the response")


class AIRecommendation(BaseModel):
    """Schema for AI personalized recommendation item."""
    title: str
    impact: str = Field("High", description="Impact rating (High, Medium, Low)")
    description: str


class AIAlert(BaseModel):
    """Schema for AI financial anomaly alert."""
    title: str
    message: str


class AIInsightsResponse(BaseModel):
    """Schema for AI Insights dashboard response."""
    financialSummary: str = Field(..., description="Executive summary generated by Groq LLM")
    healthScore: int = Field(..., ge=0, le=100, description="Financial health score (0-100)")
    recommendations: List[AIRecommendation] = Field(default_factory=list)
    alerts: List[AIAlert] = Field(default_factory=list)
